//! Versioned, validated quantization-plan artifacts.
//!
//! Plans are generated by an explicit profiling workflow and consumed during
//! model loading. A stale or unsupported plan is rejected so production
//! inference retains the model's normal mixed-format behavior.

use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    fs::{File, OpenOptions},
    io::{Read, Write},
    path::Path,
    process,
    time::{SystemTime, UNIX_EPOCH},
};

use anyhow::{Context, Result, bail, ensure};
use atlas_core::{GgufModel, GgufTensorType};
use serde_json::{Map, Value, json};
use sha2::{Digest, Sha256};

pub const QUANTIZATION_PLAN_SCHEMA_VERSION: u32 = 1;
pub const DEFAULT_MAX_ABS_LOGIT_DELTA: f32 = 1e-3;
pub const QUANTIZATION_PLAN_STATE_PENDING: &str = "pending";
pub const QUANTIZATION_PLAN_STATE_READY: &str = "ready";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct QuantizationPlanProfilerConfig {
    pub mode: String,
    pub prompt_sha256: String,
    pub decode_tokens: u32,
    pub runs: u32,
}

#[derive(Debug, Clone, PartialEq)]
pub struct QuantizationPlanTensor {
    pub group_members: Vec<String>,
    pub source_format: GgufTensorType,
    pub selected_format: GgufTensorType,
    pub selected_kernel: String,
    pub max_abs_logit_delta: f32,
    pub median_gpu_ns: u64,
    pub baseline_gpu_ns: u64,
    pub resident_bytes: u64,
    pub upload_bytes: u64,
    pub parity_digest: String,
    pub parity: bool,
    pub rejection_reason: Option<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct QuantizationPlan {
    pub schema_version: u32,
    pub state: String,
    pub model_id: String,
    pub model_sha256: String,
    pub oracle_sha256: String,
    pub hardware_identity: String,
    pub profiler_configuration: QuantizationPlanProfilerConfig,
    pub max_abs_logit_delta: f32,
    pub tensors: BTreeMap<String, QuantizationPlanTensor>,
}

impl QuantizationPlan {
    pub fn new(model_id: impl Into<String>, model_sha256: impl Into<String>) -> Self {
        Self {
            schema_version: QUANTIZATION_PLAN_SCHEMA_VERSION,
            state: QUANTIZATION_PLAN_STATE_PENDING.into(),
            model_id: model_id.into(),
            model_sha256: model_sha256.into(),
            oracle_sha256: String::new(),
            hardware_identity: String::new(),
            profiler_configuration: QuantizationPlanProfilerConfig {
                mode: QUANTIZATION_PLAN_STATE_PENDING.into(),
                prompt_sha256: String::new(),
                decode_tokens: 0,
                runs: 0,
            },
            max_abs_logit_delta: DEFAULT_MAX_ABS_LOGIT_DELTA,
            tensors: BTreeMap::new(),
        }
    }

    pub fn from_path(path: impl AsRef<Path>) -> Result<Self> {
        let path = path.as_ref();
        let value: Value = serde_json::from_slice(
            &fs::read(path)
                .with_context(|| format!("read quantization plan {}", path.display()))?,
        )
        .with_context(|| format!("parse quantization plan {}", path.display()))?;
        Self::from_value(&value)
            .with_context(|| format!("validate quantization plan {}", path.display()))
    }

    pub fn write_path(&self, path: impl AsRef<Path>) -> Result<()> {
        let path = path.as_ref();
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).with_context(|| {
                format!("create quantization plan directory {}", parent.display())
            })?;
        }
        let bytes = serde_json::to_vec_pretty(&self.to_value())?;
        let temp_path = quantization_plan_temp_path(path);
        {
            let mut file = OpenOptions::new()
                .create_new(true)
                .write(true)
                .open(&temp_path)
                .with_context(|| {
                    format!("create quantization plan temp {}", temp_path.display())
                })?;
            file.write_all(&bytes)
                .with_context(|| format!("write quantization plan {}", temp_path.display()))?;
            file.sync_all()
                .with_context(|| format!("sync quantization plan {}", temp_path.display()))?;
        }
        fs::rename(&temp_path, path).with_context(|| {
            format!(
                "atomically move quantization plan {} to {}",
                temp_path.display(),
                path.display()
            )
        })?;
        Ok(())
    }

    pub fn validate_for_model(&self, model: &GgufModel, expected_model_sha256: &str) -> Result<()> {
        self.validate_for_model_with_identity(model, expected_model_sha256, None, None)
    }

    pub fn validate_for_model_with_identity(
        &self,
        model: &GgufModel,
        expected_model_sha256: &str,
        expected_hardware_identity: Option<&str>,
        expected_oracle_sha256: Option<&str>,
    ) -> Result<()> {
        ensure!(
            self.schema_version == QUANTIZATION_PLAN_SCHEMA_VERSION,
            "unsupported quantization plan schema {}",
            self.schema_version
        );
        ensure!(
            matches!(
                self.state.as_str(),
                QUANTIZATION_PLAN_STATE_PENDING | QUANTIZATION_PLAN_STATE_READY
            ),
            "unsupported quantization plan state {}",
            self.state
        );
        ensure!(
            self.state == QUANTIZATION_PLAN_STATE_READY,
            "quantization plan is not ready: {}",
            self.state
        );
        ensure!(
            !self.model_id.is_empty(),
            "quantization plan model identity must not be empty"
        );
        ensure!(
            self.model_sha256 == expected_model_sha256,
            "quantization plan model SHA mismatch: plan={}, model={}",
            self.model_sha256,
            expected_model_sha256
        );
        ensure!(
            !self.oracle_sha256.is_empty(),
            "quantization plan oracle identity must not be empty"
        );
        if let Some(expected_oracle_sha256) = expected_oracle_sha256 {
            ensure!(
                self.oracle_sha256 == expected_oracle_sha256,
                "quantization plan oracle SHA mismatch: plan={}, oracle={}",
                self.oracle_sha256,
                expected_oracle_sha256
            );
        }
        ensure!(
            !self.hardware_identity.is_empty(),
            "quantization plan hardware identity must not be empty"
        );
        if let Some(expected_hardware_identity) = expected_hardware_identity {
            ensure!(
                self.hardware_identity == expected_hardware_identity,
                "quantization plan hardware mismatch: plan={}, hardware={}",
                self.hardware_identity,
                expected_hardware_identity
            );
        }
        ensure!(
            !self.profiler_configuration.mode.is_empty(),
            "quantization plan profiler configuration is missing a mode"
        );
        ensure!(
            !self.profiler_configuration.prompt_sha256.is_empty(),
            "quantization plan profiler configuration is missing a prompt digest"
        );
        ensure!(
            self.profiler_configuration.decode_tokens > 0,
            "quantization plan profiler configuration requires positive decode tokens"
        );
        ensure!(
            self.profiler_configuration.runs > 0,
            "quantization plan profiler configuration requires positive runs"
        );
        ensure!(
            self.max_abs_logit_delta.is_finite() && self.max_abs_logit_delta >= 0.0,
            "quantization plan logit bound must be finite and non-negative"
        );

        let mut groups = BTreeMap::<Vec<String>, BTreeSet<String>>::new();
        for (name, entry) in &self.tensors {
            let tensor = model
                .tensors
                .iter()
                .find(|tensor| tensor.name == *name)
                .with_context(|| format!("quantization plan names missing tensor `{name}`"))?;
            ensure!(
                !entry.group_members.is_empty(),
                "quantization plan group for `{name}` must list executable members"
            );
            let mut members = entry.group_members.clone();
            members.sort();
            members.dedup();
            ensure!(
                members.iter().any(|member| member == name),
                "quantization plan group for `{name}` must include the tensor itself"
            );
            for member in &members {
                ensure!(
                    self.tensors.contains_key(member),
                    "quantization plan group for `{name}` references missing tensor `{member}`"
                );
            }
            groups
                .entry(members.clone())
                .or_default()
                .insert(name.clone());
            ensure!(
                tensor.tensor_type == entry.source_format,
                "quantization plan source format mismatch for `{name}`: plan={:?}, model={:?}",
                entry.source_format,
                tensor.tensor_type
            );
            ensure!(
                supported_plan_format(name, entry.selected_format),
                "quantization plan format {:?} for `{name}` is unsupported",
                entry.selected_format
            );
            ensure!(
                !entry.selected_kernel.trim().is_empty(),
                "quantization plan selected kernel for `{name}` must not be empty"
            );
            ensure!(
                entry.max_abs_logit_delta.is_finite() && entry.max_abs_logit_delta >= 0.0,
                "quantization plan logit error for `{name}` is invalid"
            );
            ensure!(
                entry.median_gpu_ns > 0 && entry.baseline_gpu_ns > 0,
                "quantization plan timings for `{name}` must be positive"
            );
            ensure!(
                entry.resident_bytes > 0 && entry.upload_bytes > 0,
                "quantization plan evidence for `{name}` must include positive resident and upload bytes"
            );
            ensure!(
                !entry.parity_digest.trim().is_empty(),
                "quantization plan parity digest for `{name}` must not be empty"
            );
            ensure!(
                entry.parity,
                "quantization plan candidate for `{name}` lacks parity"
            );
            ensure!(
                entry.rejection_reason.is_none(),
                "quantization plan candidate for `{name}` carries a rejection reason"
            );
        }

        for (members, declaring) in groups {
            let expected = members.iter().cloned().collect::<BTreeSet<_>>();
            ensure!(
                declaring == expected,
                "quantization plan group coverage is incomplete: expected {:?}, got {:?}",
                expected,
                declaring
            );
        }

        Ok(())
    }

    pub fn selected_format(&self, tensor_name: &str) -> Option<GgufTensorType> {
        self.tensors
            .get(tensor_name)
            .map(|entry| entry.selected_format)
    }

    pub fn to_value(&self) -> Value {
        let tensors = self
            .tensors
            .iter()
            .map(|(name, entry)| {
                (
                    name.clone(),
                    json!({
                        "group_members": entry.group_members,
                        "source_format": format_name(entry.source_format),
                        "selected_format": format_name(entry.selected_format),
                        "selected_kernel": entry.selected_kernel,
                        "max_abs_logit_delta": entry.max_abs_logit_delta,
                        "median_gpu_ns": entry.median_gpu_ns,
                        "baseline_gpu_ns": entry.baseline_gpu_ns,
                        "resident_bytes": entry.resident_bytes,
                        "upload_bytes": entry.upload_bytes,
                        "parity_digest": entry.parity_digest,
                        "parity": entry.parity,
                        "rejection_reason": entry.rejection_reason,
                    }),
                )
            })
            .collect::<Map<_, _>>();
        json!({
            "schema_version": self.schema_version,
            "state": self.state,
            "model_id": self.model_id,
            "model_sha256": self.model_sha256,
            "oracle_sha256": self.oracle_sha256,
            "hardware_identity": self.hardware_identity,
            "profiler_configuration": {
                "mode": self.profiler_configuration.mode,
                "prompt_sha256": self.profiler_configuration.prompt_sha256,
                "decode_tokens": self.profiler_configuration.decode_tokens,
                "runs": self.profiler_configuration.runs,
            },
            "max_abs_logit_delta": self.max_abs_logit_delta,
            "tensors": tensors,
        })
    }

    fn from_value(value: &Value) -> Result<Self> {
        let object = value
            .as_object()
            .context("quantization plan must be an object")?;
        let schema_version = required_u32(object, "schema_version")?;
        let state = optional_string(object, "state");
        let model_id = required_string(object, "model_id")?;
        let model_sha256 = required_string(object, "model_sha256")?;
        let oracle_sha256 = optional_string(object, "oracle_sha256");
        let hardware_identity = optional_string(object, "hardware_identity");
        let max_abs_logit_delta = object
            .get("max_abs_logit_delta")
            .and_then(Value::as_f64)
            .unwrap_or(f64::from(DEFAULT_MAX_ABS_LOGIT_DELTA))
            as f32;
        let profiler_configuration = object
            .get("profiler_configuration")
            .and_then(Value::as_object)
            .map(|object| QuantizationPlanProfilerConfig {
                mode: optional_string(object, "mode"),
                prompt_sha256: optional_string(object, "prompt_sha256"),
                decode_tokens: optional_u32(object, "decode_tokens"),
                runs: optional_u32(object, "runs"),
            })
            .unwrap_or_else(|| QuantizationPlanProfilerConfig {
                mode: String::new(),
                prompt_sha256: String::new(),
                decode_tokens: 0,
                runs: 0,
            });
        let tensor_values = object
            .get("tensors")
            .and_then(Value::as_object)
            .context("quantization plan is missing object `tensors`")?;
        let mut tensors = BTreeMap::new();
        for (name, value) in tensor_values {
            let entry = value
                .as_object()
                .with_context(|| format!("quantization plan tensor `{name}` must be an object"))?;
            tensors.insert(
                name.clone(),
                QuantizationPlanTensor {
                    group_members: optional_strings(entry, "group_members"),
                    source_format: parse_format(required_string(entry, "source_format")?.as_str())?,
                    selected_format: parse_format(
                        required_string(entry, "selected_format")?.as_str(),
                    )?,
                    selected_kernel: required_string(entry, "selected_kernel")?,
                    max_abs_logit_delta: required_f32(entry, "max_abs_logit_delta")?,
                    median_gpu_ns: required_u64(entry, "median_gpu_ns")?,
                    baseline_gpu_ns: required_u64(entry, "baseline_gpu_ns")?,
                    resident_bytes: required_u64(entry, "resident_bytes")?,
                    upload_bytes: required_u64(entry, "upload_bytes")?,
                    parity_digest: required_string(entry, "parity_digest")?,
                    parity: entry
                        .get("parity")
                        .and_then(Value::as_bool)
                        .unwrap_or(false),
                    rejection_reason: entry
                        .get("rejection_reason")
                        .and_then(Value::as_str)
                        .map(str::to_owned),
                },
            );
        }
        Ok(Self {
            schema_version,
            state: if state.is_empty() {
                QUANTIZATION_PLAN_STATE_READY.into()
            } else {
                state
            },
            model_id,
            model_sha256,
            oracle_sha256,
            hardware_identity,
            profiler_configuration,
            max_abs_logit_delta,
            tensors,
        })
    }
}

pub fn default_sidecar_path(model_path: impl AsRef<Path>) -> std::path::PathBuf {
    let model_path = model_path.as_ref();
    let mut path = model_path.to_path_buf();
    path.set_extension("quantization-plan.json");
    path
}

pub fn sha256_file(path: impl AsRef<Path>) -> Result<String> {
    let mut file = File::open(path.as_ref())
        .with_context(|| format!("open model for SHA-256 {}", path.as_ref().display()))?;
    let mut digest = Sha256::new();
    let mut buffer = [0u8; 1024 * 1024];
    loop {
        let count = file.read(&mut buffer)?;
        if count == 0 {
            break;
        }
        digest.update(&buffer[..count]);
    }
    Ok(format!("{:x}", digest.finalize()))
}

fn supported_plan_format(name: &str, format: GgufTensorType) -> bool {
    matches!(format, GgufTensorType::Q4_0 | GgufTensorType::Q6K)
        || (name == "per_layer_model_proj.weight" && format == GgufTensorType::F16)
}

fn format_name(format: GgufTensorType) -> &'static str {
    match format {
        GgufTensorType::F32 => "f32",
        GgufTensorType::F16 => "f16",
        GgufTensorType::Q4_0 => "q4_0",
        GgufTensorType::Q8_0 => "q8_0",
        GgufTensorType::Q6K => "q6_k",
    }
}

fn parse_format(value: &str) -> Result<GgufTensorType> {
    match value {
        "f32" => Ok(GgufTensorType::F32),
        "f16" => Ok(GgufTensorType::F16),
        "q4_0" => Ok(GgufTensorType::Q4_0),
        "q8_0" => Ok(GgufTensorType::Q8_0),
        "q6_k" => Ok(GgufTensorType::Q6K),
        _ => bail!("unsupported quantization plan format `{value}`"),
    }
}

fn quantization_plan_temp_path(path: &Path) -> std::path::PathBuf {
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("quantization-plan.json");
    let stamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    path.with_file_name(format!(".{file_name}.{stamp}.{}.tmp", process::id()))
}

fn required_string(object: &Map<String, Value>, key: &str) -> Result<String> {
    object
        .get(key)
        .and_then(Value::as_str)
        .map(str::to_owned)
        .with_context(|| format!("quantization plan is missing string `{key}`"))
}

fn optional_string(object: &Map<String, Value>, key: &str) -> String {
    object
        .get(key)
        .and_then(Value::as_str)
        .unwrap_or_default()
        .to_owned()
}

fn optional_strings(object: &Map<String, Value>, key: &str) -> Vec<String> {
    object
        .get(key)
        .and_then(Value::as_array)
        .map(|values| {
            values
                .iter()
                .filter_map(Value::as_str)
                .map(str::to_owned)
                .collect()
        })
        .unwrap_or_default()
}

fn required_u32(object: &Map<String, Value>, key: &str) -> Result<u32> {
    object
        .get(key)
        .and_then(Value::as_u64)
        .and_then(|v| u32::try_from(v).ok())
        .with_context(|| format!("quantization plan is missing integer `{key}`"))
}

fn optional_u32(object: &Map<String, Value>, key: &str) -> u32 {
    object
        .get(key)
        .and_then(Value::as_u64)
        .and_then(|v| u32::try_from(v).ok())
        .unwrap_or_default()
}

fn required_u64(object: &Map<String, Value>, key: &str) -> Result<u64> {
    object
        .get(key)
        .and_then(Value::as_u64)
        .with_context(|| format!("quantization plan is missing integer `{key}`"))
}

fn required_f32(object: &Map<String, Value>, key: &str) -> Result<f32> {
    object
        .get(key)
        .and_then(Value::as_f64)
        .map(|v| v as f32)
        .with_context(|| format!("quantization plan is missing number `{key}`"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use atlas_core::{GgufTensorType, GgufWriter};
    use std::{fs, process};

    fn test_model() -> GgufModel {
        let mut writer = GgufWriter::new();
        writer
            .push_tensor(
                "group_a.weight",
                vec![32],
                GgufTensorType::Q4_0,
                vec![0; GgufTensorType::Q4_0.block_bytes()],
            )
            .unwrap();
        writer
            .push_tensor(
                "group_b.weight",
                vec![32],
                GgufTensorType::Q4_0,
                vec![0; GgufTensorType::Q4_0.block_bytes()],
            )
            .unwrap();
        GgufModel::from_bytes(writer.finish().unwrap()).unwrap()
    }

    fn ready_plan() -> QuantizationPlan {
        let mut plan = QuantizationPlan::new("gemma", "model-sha");
        plan.state = QUANTIZATION_PLAN_STATE_READY.into();
        plan.oracle_sha256 = "oracle-sha".into();
        plan.hardware_identity = "Apple GPU 42".into();
        plan.profiler_configuration = QuantizationPlanProfilerConfig {
            mode: "auto".into(),
            prompt_sha256: "prompt-sha".into(),
            decode_tokens: 32,
            runs: 2,
        };
        plan.tensors.insert(
            "group_a.weight".into(),
            QuantizationPlanTensor {
                group_members: vec!["group_a.weight".into(), "group_b.weight".into()],
                source_format: GgufTensorType::Q4_0,
                selected_format: GgufTensorType::Q4_0,
                selected_kernel: "matvec_q4_0_16row".into(),
                max_abs_logit_delta: 0.0005,
                median_gpu_ns: 90,
                baseline_gpu_ns: 100,
                resident_bytes: 1024,
                upload_bytes: 512,
                parity_digest: "parity-digest".into(),
                parity: true,
                rejection_reason: None,
            },
        );
        plan.tensors.insert(
            "group_b.weight".into(),
            QuantizationPlanTensor {
                group_members: vec!["group_a.weight".into(), "group_b.weight".into()],
                source_format: GgufTensorType::Q4_0,
                selected_format: GgufTensorType::Q4_0,
                selected_kernel: "matvec_q4_0_16row".into(),
                max_abs_logit_delta: 0.0005,
                median_gpu_ns: 90,
                baseline_gpu_ns: 100,
                resident_bytes: 1024,
                upload_bytes: 512,
                parity_digest: "parity-digest".into(),
                parity: true,
                rejection_reason: None,
            },
        );
        plan
    }

    #[test]
    fn plan_round_trips_and_validates_ready_state() {
        let plan = ready_plan();
        let decoded = QuantizationPlan::from_value(&plan.to_value()).unwrap();
        assert_eq!(decoded, plan);
        plan.validate_for_model_with_identity(
            &test_model(),
            "model-sha",
            Some("Apple GPU 42"),
            Some("oracle-sha"),
        )
        .unwrap();
        assert_eq!(
            default_sidecar_path("model.gguf").to_string_lossy(),
            "model.quantization-plan.json"
        );
    }

    #[test]
    fn plan_rejects_stale_sha_and_hardware() {
        let plan = ready_plan();
        let model = test_model();
        let sha_error = plan
            .validate_for_model_with_identity(
                &model,
                "different-sha",
                Some("Apple GPU 42"),
                Some("oracle-sha"),
            )
            .unwrap_err()
            .to_string();
        assert!(sha_error.contains("model SHA mismatch"));

        let hardware_error = plan
            .validate_for_model_with_identity(
                &model,
                "model-sha",
                Some("different-gpu"),
                Some("oracle-sha"),
            )
            .unwrap_err()
            .to_string();
        assert!(hardware_error.contains("hardware mismatch"));
    }

    #[test]
    fn plan_rejects_pending_state() {
        let mut plan = ready_plan();
        plan.state = QUANTIZATION_PLAN_STATE_PENDING.into();
        let error = plan
            .validate_for_model_with_identity(
                &test_model(),
                "model-sha",
                Some("Apple GPU 42"),
                Some("oracle-sha"),
            )
            .unwrap_err()
            .to_string();
        assert!(error.contains("not ready"));
    }

    #[test]
    fn plan_rejects_incomplete_group_coverage() {
        let mut plan = ready_plan();
        plan.tensors.insert(
            "group_b.weight".into(),
            QuantizationPlanTensor {
                group_members: vec!["group_b.weight".into()],
                source_format: GgufTensorType::Q4_0,
                selected_format: GgufTensorType::Q4_0,
                selected_kernel: "matvec_q4_0_16row".into(),
                max_abs_logit_delta: 0.0005,
                median_gpu_ns: 90,
                baseline_gpu_ns: 100,
                resident_bytes: 1024,
                upload_bytes: 512,
                parity_digest: "parity-digest".into(),
                parity: true,
                rejection_reason: None,
            },
        );
        let error = plan
            .validate_for_model_with_identity(
                &test_model(),
                "model-sha",
                Some("Apple GPU 42"),
                Some("oracle-sha"),
            )
            .unwrap_err()
            .to_string();
        assert!(error.contains("group coverage is incomplete"));
    }

    #[test]
    fn plan_rejects_unsupported_selected_format() {
        let mut plan = ready_plan();
        plan.tensors
            .get_mut("group_a.weight")
            .unwrap()
            .selected_format = GgufTensorType::Q8_0;
        let error = plan
            .validate_for_model_with_identity(
                &test_model(),
                "model-sha",
                Some("Apple GPU 42"),
                Some("oracle-sha"),
            )
            .unwrap_err()
            .to_string();
        assert!(error.contains("unsupported"));
    }

    #[test]
    fn plan_rejects_invalid_timing_and_evidence() {
        let mut plan = ready_plan();
        plan.tensors
            .get_mut("group_a.weight")
            .unwrap()
            .median_gpu_ns = 0;
        plan.tensors
            .get_mut("group_a.weight")
            .unwrap()
            .resident_bytes = 0;
        let error = plan
            .validate_for_model_with_identity(
                &test_model(),
                "model-sha",
                Some("Apple GPU 42"),
                Some("oracle-sha"),
            )
            .unwrap_err()
            .to_string();
        assert!(error.contains("must be positive"));
    }

    #[test]
    fn plan_rejects_failed_parity() {
        let mut plan = ready_plan();
        plan.tensors.get_mut("group_a.weight").unwrap().parity = false;
        plan.tensors
            .get_mut("group_a.weight")
            .unwrap()
            .rejection_reason = Some("parity mismatch".into());
        let error = plan
            .validate_for_model_with_identity(
                &test_model(),
                "model-sha",
                Some("Apple GPU 42"),
                Some("oracle-sha"),
            )
            .unwrap_err()
            .to_string();
        assert!(error.contains("lacks parity"));
    }

    #[test]
    fn plan_write_path_is_atomic_and_reloads() {
        let dir = std::env::temp_dir().join(format!("atlas-quantization-plan-{}", process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        let path = dir.join("model.quantization-plan.json");
        let mut first = ready_plan();
        first.model_sha256 = "first-sha".into();
        first.write_path(&path).unwrap();
        assert_eq!(QuantizationPlan::from_path(&path).unwrap(), first);

        let mut second = ready_plan();
        second.model_sha256 = "second-sha".into();
        second
            .tensors
            .get_mut("group_a.weight")
            .unwrap()
            .selected_kernel = "matvec_q4_0_16row_simdgroup_tiled".into();
        second.write_path(&path).unwrap();
        assert_eq!(QuantizationPlan::from_path(&path).unwrap(), second);

        let contents = fs::read_to_string(&path).unwrap();
        assert!(contents.contains("second-sha"));
        let temp_files = fs::read_dir(&dir)
            .unwrap()
            .filter_map(Result::ok)
            .map(|entry| entry.file_name().to_string_lossy().into_owned())
            .filter(|name| name.contains(".tmp"))
            .collect::<Vec<_>>();
        assert!(
            temp_files.is_empty(),
            "unexpected temp files left behind: {temp_files:?}"
        );
        let _ = fs::remove_dir_all(&dir);
    }
}
